title       = "marinemeteo"
baseURL     = "https://marinemeteo-cli.tamnd.com/"
description = "A command line for marinemeteo."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/marinemeteo-cli"
